package com.voxgest.dryrun

import android.content.Context
import org.json.JSONObject
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.security.MessageDigest
import kotlin.math.abs

enum class StandardFslParityStatus {
    PASS,
    FAIL,
    BLOCKED
}

data class StandardFslParityCheck(
    val status: StandardFslParityStatus,
    val marker: String,
    val evidence: String
)

data class StandardFslParityReport(
    val feature: StandardFslParityCheck,
    val tflite: StandardFslParityCheck
) {
    val passed: Boolean
        get() = feature.status == StandardFslParityStatus.PASS &&
            tflite.status == StandardFslParityStatus.PASS
}

/**
 * Numeric harness for fixtures generated by the canonical Python builder.
 * It is main-source deliberately: the standard launcher must not activate
 * FullSign225 unless both Android numeric checks pass.
 */
class StandardFslParityHarness(private val context: Context) {
    private val root = GradingRecognitionProfiles.STANDARD_ASSET_ROOT

    fun run(): StandardFslParityReport {
        val feature = runFeatureParity()
        val tflite = if (feature.status == StandardFslParityStatus.PASS) {
            runTfliteParity()
        } else {
            StandardFslParityCheck(
                StandardFslParityStatus.BLOCKED,
                TFLITE_MARKER,
                "blocked_by_feature_parity status=${feature.status}"
            )
        }
        return StandardFslParityReport(feature, tflite)
    }

    fun runFeatureParity(): StandardFslParityCheck {
        val asset = "$root/golden_fullsign225_feature_fixture_f32.bin"
        val metadataAsset = "$root/golden_fullsign225_feature_fixture.json"
        return try {
            val metadata = context.assets.open(metadataAsset).bufferedReader().use {
                JSONObject(it.readText())
            }
            require(metadata.getString("feature_version") == StandardFullSign225Contract.FEATURE_VERSION)
            require(metadata.getInt("float_count") == FEATURE_FIXTURE_FLOAT_COUNT)
            require(metadata.getJSONArray("cases").let { cases ->
                List(cases.length()) { cases.getString(it) }
            } == listOf("both", "left_only", "right_only", "no_hands", "missing_pose"))
            val expectedSha = metadata.getString("binary_sha256")
            val actualSha = sha256Asset(asset)
            require(actualSha == expectedSha) { "feature fixture SHA-256 mismatch" }
            val values = readFloats(asset, FEATURE_FIXTURE_FLOAT_COUNT)
            val pose = values.copyOfRange(0, 99).toPoints(33)
            val left = values.copyOfRange(99, 162).toPoints(21)
            val right = values.copyOfRange(162, 225).toPoints(21)
            val actual = listOf(
                StandardFullSign225FeatureBuilder.build(frame(pose, left, right)).vector,
                StandardFullSign225FeatureBuilder.build(frame(pose, left, null)).vector,
                StandardFullSign225FeatureBuilder.build(frame(pose, null, right)).vector,
                StandardFullSign225FeatureBuilder.build(frame(pose, null, null)).vector,
                StandardFullSign225FeatureBuilder.build(frame(null, left, right)).vector
            )
            val expected = List(5) { case ->
                val start = 225 + case * StandardFullSign225Contract.FEATURE_SIZE
                values.copyOfRange(start, start + StandardFullSign225Contract.FEATURE_SIZE)
            }
            val errors = actual.indices.map { index -> maxAbs(actual[index], expected[index]) }
            val maxError = errors.maxOrNull() ?: Float.POSITIVE_INFINITY
            val leftOnlySlots = slotsFor(actual[1])
            val rightOnlySlots = slotsFor(actual[2])
            require(leftOnlySlots == "left_only") {
                "left-only fixture populated $leftOnlySlots"
            }
            require(rightOnlySlots == "right_only") {
                "right-only fixture populated $rightOnlySlots"
            }
            StandardFslParityCheck(
                if (maxError <= FEATURE_MAX_ABS_ERROR) {
                    StandardFslParityStatus.PASS
                } else {
                    StandardFslParityStatus.FAIL
                },
                FEATURE_MARKER,
                "fixture=$asset sha256=$actualSha cases=both,left_only,right_only,no_hands,missing_pose " +
                    "max_abs_error=$maxError threshold=$FEATURE_MAX_ABS_ERROR " +
                    "left_only=$leftOnlySlots right_only=$rightOnlySlots no_hand_swapping=true " +
                    "model_input=unmirrored"
            )
        } catch (error: java.io.FileNotFoundException) {
            StandardFslParityCheck(
                StandardFslParityStatus.BLOCKED,
                FEATURE_MARKER,
                "missing_fixture=$asset or $metadataAsset"
            )
        } catch (error: Throwable) {
            StandardFslParityCheck(
                StandardFslParityStatus.FAIL,
                FEATURE_MARKER,
                "error=${error.javaClass.simpleName}:${error.message}"
            )
        }
    }

    fun runTfliteParity(): StandardFslParityCheck {
        val readiness = StandardFslArtifactGate.inspect(context)
        if (!readiness.canOpenRuntimeForParity) {
            return StandardFslParityCheck(StandardFslParityStatus.BLOCKED, TFLITE_MARKER, readiness.evidence)
        }
        val windowAsset = "$root/golden_window_f32.bin"
        val expectedAsset = "$root/golden_expected.json"
        return try {
            val flat = readFloats(
                windowAsset,
                StandardFullSign225Contract.SEQUENCE_LENGTH * StandardFullSign225Contract.FEATURE_SIZE
            )
            val window = Array(StandardFullSign225Contract.SEQUENCE_LENGTH) { frame ->
                val start = frame * StandardFullSign225Contract.FEATURE_SIZE
                flat.copyOfRange(start, start + StandardFullSign225Contract.FEATURE_SIZE)
            }
            val expectedJson = context.assets.open(expectedAsset).bufferedReader().use {
                JSONObject(it.readText())
            }
            val expectedNode = expectedJson.getJSONObject("expected_output")
            val expectedArray = expectedNode.getJSONArray("probabilities")
            val expected = FloatArray(expectedArray.length()) { expectedArray.getDouble(it).toFloat() }
            require(expected.size == 105)
            val expectedTop1 = expectedNode.getInt("top1_index")
            val expectedTop1Label = expectedNode.getString("top1_label")
            val threshold = expectedJson.getJSONObject("android_parity_thresholds")
                .getDouble("maximum_absolute_probability_error").toFloat()
            val meanThreshold = expectedJson.getJSONObject("android_parity_thresholds")
                .getDouble("maximum_mean_absolute_probability_error").toFloat()
            require(threshold > 0f && threshold <= TFLITE_MAX_ABS_ERROR_CEILING) {
                "parity threshold $threshold exceeds project ceiling $TFLITE_MAX_ABS_ERROR_CEILING"
            }
            require(meanThreshold > 0f && meanThreshold <= TFLITE_MAX_ABS_ERROR_CEILING) {
                "mean parity threshold $meanThreshold exceeds project ceiling $TFLITE_MAX_ABS_ERROR_CEILING"
            }
            StandardFslTfliteRuntime(context).use { runtime ->
                val actual = runtime.infer(window)
                val maxDifference = actual.probabilities.indices.maxOf { index ->
                    abs(actual.probabilities[index] - expected[index])
                }
                val meanDifference = actual.probabilities.indices
                    .map { index -> abs(actual.probabilities[index] - expected[index]) }
                    .average()
                val top1Agreement = actual.top1.index == expectedTop1 &&
                    actual.top1.label == expectedTop1Label
                val passed = top1Agreement && maxDifference <= threshold && meanDifference <= meanThreshold
                StandardFslParityCheck(
                    if (passed) StandardFslParityStatus.PASS else StandardFslParityStatus.FAIL,
                    TFLITE_MARKER,
                    "fixture=$windowAsset top1_index=${actual.top1.index} expected_top1_index=$expectedTop1 " +
                        "top1_label=${actual.top1.label} expected_top1_label=$expectedTop1Label " +
                        "top1_agreement=$top1Agreement max_probability_difference=$maxDifference " +
                        "max_threshold=$threshold mean_probability_difference=$meanDifference " +
                        "mean_threshold=$meanThreshold latency_ms=${actual.latencyMs}"
                )
            }
        } catch (error: java.io.FileNotFoundException) {
            StandardFslParityCheck(
                StandardFslParityStatus.BLOCKED,
                TFLITE_MARKER,
                "missing_fixture=$windowAsset or $expectedAsset"
            )
        } catch (error: Throwable) {
            StandardFslParityCheck(
                StandardFslParityStatus.FAIL,
                TFLITE_MARKER,
                "error=${error.javaClass.simpleName}:${error.message}"
            )
        }
    }

    private fun frame(
        pose: List<LandmarkPoint>?,
        left: List<LandmarkPoint>?,
        right: List<LandmarkPoint>?
    ): LandmarkFrame = LandmarkFrame(pose, left, right, 0L)

    private fun readFloats(asset: String, count: Int): FloatArray {
        val bytes = context.assets.open(asset).use { it.readBytes() }
        require(bytes.size == count * Float.SIZE_BYTES) {
            "$asset has ${bytes.size} bytes; expected ${count * Float.SIZE_BYTES}"
        }
        val buffer = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN)
        return FloatArray(count) { buffer.float }
    }

    private fun FloatArray.toPoints(count: Int): List<LandmarkPoint> {
        require(size == count * 3)
        return List(count) { index ->
            LandmarkPoint(this[index * 3], this[index * 3 + 1], this[index * 3 + 2])
        }
    }

    private fun maxAbs(actual: FloatArray, expected: FloatArray): Float {
        require(actual.size == expected.size)
        return actual.indices.maxOf { index -> abs(actual[index] - expected[index]) }
    }

    private fun slotsFor(vector: FloatArray): String {
        val left = vector.copyOfRange(99, 162).any { it != 0f }
        val right = vector.copyOfRange(162, 225).any { it != 0f }
        return when {
            left && !right -> "left_only"
            !left && right -> "right_only"
            left && right -> "both"
            else -> "neither"
        }
    }

    private fun sha256Asset(asset: String): String {
        val digest = MessageDigest.getInstance("SHA-256")
        context.assets.open(asset).use { input ->
            val buffer = ByteArray(DEFAULT_BUFFER_SIZE)
            while (true) {
                val count = input.read(buffer)
                if (count < 0) break
                if (count > 0) digest.update(buffer, 0, count)
            }
        }
        return digest.digest().joinToString("") { "%02x".format(it) }
    }

    companion object {
        private const val FEATURE_FIXTURE_FLOAT_COUNT = 1350
        private const val FEATURE_MAX_ABS_ERROR = 1.0e-6f
        private const val TFLITE_MAX_ABS_ERROR_CEILING = 1.0e-5f
        const val FEATURE_MARKER = "ANDROID_FEATURE_PARITY_FULLSIGN225"
        const val TFLITE_MARKER = "ANDROID_TFLITE_PARITY_FULLSIGN225"
    }
}
